apiVersion: v1
kind: Service
metadata:
  name: {{ include "deluge.fullname" . }}-http
  labels:
    {{- include "deluge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
    
  selector:
    {{- include "deluge.selectorLabels" . | nindent 4 }}